#
# MAINTAINER        cucy <zhouru1991@vip.qq.com>
# Docker version 1.12.3
#
# Dockerizing CentOS7.2: Dockerfile for building CentOS images
##

# 基础镜像
FROM   aa/aa:1.1
MAINTAINER cucy <zhouru1991@vip.qq.com>  # 谁创建，谁维护

# 环境变量可以写多个
ENV TZ "Asia/Shanghai"     
# ENV TERM xterm


#EXPOSE 3306 10051 80

#ENTRYPOINT ["/scripts/start"]
