#
# MAINTAINER        cucy <zhouru1991@vip.qq.com>
# Docker version 1.12.3
#
# Dockerizing CentOS7.2: Dockerfile for building busybox
#

# 基础镜像
FROM       busybox:latest

MAINTAINER cucy <zhouru1991@vip.qq.com>  # 谁创建，谁维护


ADD http://ftp.tsukuba.wide.ad.jp/software/jenkins/plugins/maven-plugin/2.14/maven-plugin.hpi /