#
# MAINTAINER        cucy <zhouru1991@vip.qq.com>
# Docker version 1.12.3
#
# Dockerizing CentOS7.2: Dockerfile for building busybox
#

# 基础镜像
FROM       busybox:latest

MAINTAINER cucy <zhouru1991@vip.qq.com>  # 谁创建，谁维护


ADD http://www.hop5.in/yum/el6/kernel-ml-aufs-3.10.5-3.el6.x86_64.rpm /
